name: Notion GitHub Issues Automation
author: Sajan Toor
description: Gets issues from GitHub and puts them in your Notion database.
branding:
  color: gray-dark
  icon: check-circle

runs:
  using: node12
  main: ./index.ts
