name: Notion GitHub Issues Automation
author: Sajan Toor
description: Gets issues from GitHub and puts them in your Notion database.
branding:
  color: gray-dark
  icon: check-circle

inputs: 
  repo: 
    description: "Your current repository."
    required: true
  NOTION_API_KEY: 
    description: "Your Notion API Key"
    required: true
  NOTION_DATABASE: 
    description: "Your Notion database ID"
    required: true
  NOTION_PAGE_ID: 
    description: "The ID of the page that contains your database"
    required: false

runs:
  using: node12
  main: build/index.ts